name: Docker Build and Push

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest .

      # 3. List Docker images
      - name: List Docker Images
        run: |
          docker images

      # 4. Run Docker container for testing
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name my-python-container \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest

      # 5. Test application
      - name: Test Application
        run: |
          sleep 5
          curl http://localhost:5000

      # 6. Stop test container
      - name: Stop Docker Container
        run: |
          docker stop my-python-container
          docker rm my-python-container

      # 7. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
